services:
  game-db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=game-db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/game-postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
    networks:
      - app-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: game_system_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gamesystem.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    networks:
      - app-net

networks:
  app-net:
    external: true