services:
  - type: web
    name: card-game-backend
    env: java
    rootDir: backend
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    plan: free
