services:
  - type: web
    name: card-game-backend
    env: java
    region: oregon
    plan: free
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar