app:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "https://your-frontend-domain.com"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
  google:
    client-id: ${GAME_SYSTEM_GOOGLE_CLIENT_ID}
    client-secret: ${GAME_SYSTEM_GOOGLE_CLIENT_SECRET}
spring:
  datasource:
    url: jdbc:postgresql://${GAME_SYSTEM_DB_HOST}:${GAME_SYSTEM_DB_PORT}/${GAME_SYSTEM_DB_NAME}
    username: ${GAME_SYSTEM_DB_USERNAME}
    password: ${GAME_SYSTEM_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariPool-19
  # ===============================
  # Hibernate Configuration
  # ===============================
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true